### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by lb42** [christofs/innerlife#1]
i checked out https://github.com/christofs/innerlife.git & tried to run it
~~~~
(base) lou@Thimk:~/Public/ELTeC-data/innerlife$    python analysis.py 
Done: rom
Traceback (most recent call last):
  File "analysis.py", line 146, in <module>
    main()
  File "analysis.py", line 142, in main
    plot_seaborn(corpus, comparison, vals1, vals2, med1, med2, samplesize, p) 
  File "analysis.py", line 121, in plot_seaborn
    plot = sns.displot([vals1, vals2], kind="kde", fill=True, rug=False, linewidth=2)
AttributeError: module 'seaborn' has no attribute 'displot'
(base) lou@Thimk:~/Public/ELTeC-data/innerlife$ 
~~~~

**Comment by christofs** [comment]
Note for others: Upgrading to seaborn 1.12 solved this.
